services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Ibexa\TwigComponents\Component\Registry:

    Ibexa\TwigComponents\Component\TwigComponent:
        abstract: true
        lazy: true
        arguments:
            $parameters: []

    Ibexa\TwigComponents\Component\ScriptComponent:
        abstract: true
        lazy: true

    Ibexa\TwigComponents\Component\LinkComponent:
        abstract: true
        lazy: true
    
    Ibexa\TwigComponents\Component\ControllerComponent:
        abstract: true
        lazy: true
        arguments:
            $parameters: [ ]
            
    Ibexa\TwigComponents\Component\HtmlComponent:
        abstract: true
        lazy: true

    Ibexa\Bundle\TwigComponents\Templating\Twig\ComponentExtension:
        tags:
            - { name: twig.extension }

    Ibexa\TwigComponents\Component\Renderer\DefaultRenderer:

    Ibexa\Contracts\TwigComponents\Renderer\RendererInterface: '@Ibexa\TwigComponents\Component\Renderer\DefaultRenderer'
